###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin6.ecn.purdue.edu)
#  Generated on:      Tue Apr 24 00:20:54 2018
#  Design:            shabang
#  Command:           floorPlan -r 1.0 0.3 50 50 50 50
###############################################################

Version: 8

Head Box: 0.0000 0.0000 3744.0000 3492.0000
IO Box: 300.0000 90.0000 3444.0000 3192.0000
Core Box: 350.4000 141.0000 3393.6000 3141.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 350.4000 141.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_1 core 350.4000 171.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_2 core 350.4000 201.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_3 core 350.4000 231.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_4 core 350.4000 261.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_5 core 350.4000 291.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_6 core 350.4000 321.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_7 core 350.4000 351.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_8 core 350.4000 381.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_9 core 350.4000 411.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_10 core 350.4000 441.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_11 core 350.4000 471.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_12 core 350.4000 501.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_13 core 350.4000 531.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_14 core 350.4000 561.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_15 core 350.4000 591.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_16 core 350.4000 621.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_17 core 350.4000 651.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_18 core 350.4000 681.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_19 core 350.4000 711.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_20 core 350.4000 741.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_21 core 350.4000 771.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_22 core 350.4000 801.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_23 core 350.4000 831.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_24 core 350.4000 861.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_25 core 350.4000 891.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_26 core 350.4000 921.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_27 core 350.4000 951.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_28 core 350.4000 981.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_29 core 350.4000 1011.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_30 core 350.4000 1041.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_31 core 350.4000 1071.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_32 core 350.4000 1101.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_33 core 350.4000 1131.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_34 core 350.4000 1161.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_35 core 350.4000 1191.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_36 core 350.4000 1221.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_37 core 350.4000 1251.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_38 core 350.4000 1281.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_39 core 350.4000 1311.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_40 core 350.4000 1341.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_41 core 350.4000 1371.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_42 core 350.4000 1401.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_43 core 350.4000 1431.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_44 core 350.4000 1461.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_45 core 350.4000 1491.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_46 core 350.4000 1521.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_47 core 350.4000 1551.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_48 core 350.4000 1581.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_49 core 350.4000 1611.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_50 core 350.4000 1641.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_51 core 350.4000 1671.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_52 core 350.4000 1701.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_53 core 350.4000 1731.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_54 core 350.4000 1761.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_55 core 350.4000 1791.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_56 core 350.4000 1821.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_57 core 350.4000 1851.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_58 core 350.4000 1881.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_59 core 350.4000 1911.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_60 core 350.4000 1941.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_61 core 350.4000 1971.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_62 core 350.4000 2001.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_63 core 350.4000 2031.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_64 core 350.4000 2061.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_65 core 350.4000 2091.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_66 core 350.4000 2121.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_67 core 350.4000 2151.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_68 core 350.4000 2181.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_69 core 350.4000 2211.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_70 core 350.4000 2241.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_71 core 350.4000 2271.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_72 core 350.4000 2301.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_73 core 350.4000 2331.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_74 core 350.4000 2361.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_75 core 350.4000 2391.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_76 core 350.4000 2421.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_77 core 350.4000 2451.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_78 core 350.4000 2481.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_79 core 350.4000 2511.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_80 core 350.4000 2541.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_81 core 350.4000 2571.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_82 core 350.4000 2601.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_83 core 350.4000 2631.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_84 core 350.4000 2661.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_85 core 350.4000 2691.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_86 core 350.4000 2721.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_87 core 350.4000 2751.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_88 core 350.4000 2781.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_89 core 350.4000 2811.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_90 core 350.4000 2841.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_91 core 350.4000 2871.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_92 core 350.4000 2901.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_93 core 350.4000 2931.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_94 core 350.4000 2961.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_95 core 350.4000 2991.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_96 core 350.4000 3021.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_97 core 350.4000 3051.0000 N 1268 1 2.4000 0.0000
DefRow: ROW_98 core 350.4000 3081.0000 FS 1268 1 2.4000 0.0000
DefRow: ROW_99 core 350.4000 3111.0000 N 1268 1 2.4000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: X 1.2000 1560 2.4000 1 3
Track: Y 1.5000 1164 3.0000 1 3
Track: Y 1.5000 1164 3.0000 1 2
Track: X 1.2000 1560 2.4000 1 2
Track: X 1.2000 1560 2.4000 1 1
Track: Y 1.5000 1164 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: Y 3492.1500 1 35.8500
GCellGrid: Y 96.3000 71 48.0000
GCellGrid: Y -0.1500 2 48.4500
GCellGrid: X 3744.1500 1 48.1500
GCellGrid: X 96.0000 76 48.0000
GCellGrid: X -0.1500 2 48.1500

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd
PhysicalNet: _FILLS_RESERVED

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="shabang" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x7 orient=R0>
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .shabang15935.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: D22 PADNC 3150.0000 3192.0000 N R0 - 00
IO: D3 PADNC 2856.0000 3192.0000 N R0 - 00
IO: U4 PADINC 2562.0000 3192.0000 N R0 - 00
IO: D2 PADNC 2268.0000 3192.0000 N R0 - 00
IO: G0 PADGND 1974.0000 3192.0000 N R0 - 00
IO: P0 PADVDD 1680.0000 3192.0000 N R0 - 00
IO: D1 PADNC 1386.0000 3192.0000 N R0 - 00
IO: U3 PADOUT 1092.0000 3192.0000 N R0 - 00
IO: D0 PADNC 798.0000 3192.0000 N R0 - 00
IO: D21 PADNC 504.0000 3192.0000 N R0 - 00
IO: co2 PADFC 3444.0000 3192.0000 NE R270 - 00
IO: D19 PADNC 0.0000 2920.8000 W R90 - 00
IO: D7 PADNC 0.0000 2649.7500 W R90 - 00
IO: D13 PADOUT 0.0000 2378.7000 W R90 - 00
IO: D6 PADNC 0.0000 2107.6500 W R90 - 00
IO: G1 PADGND 0.0000 1836.6000 W R90 - 00
IO: P1 PADVDD 0.0000 1565.5500 W R90 - 00
IO: D5 PADNC 0.0000 1294.5000 W R90 - 00
IO: U1 PADOUT 0.0000 1023.4500 W R90 - 00
IO: D4 PADNC 0.0000 752.4000 W R90 - 00
IO: D20 PADNC 0.0000 481.2000 W R90 - 00
IO: co1 PADFC 0.0000 3192.0000 NW R0 - 00
IO: D15 PADNC 3017.5500 0.0000 S R270 - 00
IO: D16 PADNC 2591.1000 0.0000 S R270 - 00
IO: D18 PADNC 2374.6500 0.0000 S R180 - 00
IO: D11 PADNC 2158.2000 0.0000 S R180 - 00
IO: U2 PADOUT 1941.7500 0.0000 S R180 - 00
IO: D10 PADNC 1725.3000 0.0000 S R180 - 00
IO: G2 PADGND 1508.8500 0.0000 S R180 - 00
IO: P2 PADVDD 1292.4000 0.0000 S R180 - 00
IO: D9 PADNC 1075.9500 0.0000 S R180 - 00
IO: U6 PADINC 859.5000 0.0000 S R180 - 00
IO: D8 PADNC 643.0500 0.0000 S R180 - 00
IO: D17 PADNC 426.6000 0.0000 S R180 - 00
IO: co3 PADFC 0.0000 0.0000 SW R90 - 00
IO: U9 PADINC 3444.0000 2860.6500 E R270 - 00
IO: U8 PADINC 3444.0000 2529.3000 E R270 - 00
IO: D14 PADNC 3444.0000 2197.9500 E R270 - 00
IO: G3 PADGND 3444.0000 1866.6000 E R270 - 00
IO: P3 PADVDD 3444.0000 1535.4000 E R270 - 00
IO: U5 PADINC 3444.0000 1204.0500 E R270 - 00
IO: U7 PADINC 3444.0000 872.7000 E R270 - 00
IO: D12 PADNC 3444.0000 541.3500 E R270 - 00
IO: co4 PADFC 3444.0000 0.0000 SE R180 - 00

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="w_clk" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="r_clk" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="n_rst" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="Ethernet_In" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="rx_d_plus" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="rx_d_minus" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="tx_d_plus" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="tx_d_minus" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
  <Pin name="is_txing" status="fixed" >
    <Port>
      <Pref x=0.0000 y=0.0000 width=0.0000 depth=0.0000 />
    </Port>
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="shabang">
	<prop name="optimization_trialRoute_guide_flow" type=Int value=1 />
	<prop name="CUT_ROWS" type=Int value=0 />
	<prop name="TDRCAppName" type=String value="OPT_LA:1 GPS_LA:2 NRImport:3 " />
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-inst|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: vdd -type tiehi -all
GlobalNetConnection: vdd -pin vdd -type pgpin -all -override
GlobalNetConnection: gnd -type tielo -all
GlobalNetConnection: gnd -pin gnd -type pgpin -all -override

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
