###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin6.ecn.purdue.edu)
#  Generated on:      Wed Apr 25 15:53:47 2018
#  Design:            shabang
#  Command:           floorPlan -r 1.0 0.7 100 100 100 100
###############################################################

Version: 8

Head Box: 0.0000 0.0000 3840.0000 3840.0000
IO Box: 300.0000 300.0000 3540.0000 3540.0000
Core Box: 300.0000 300.0000 3540.0000 3540.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 300.0000 300.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_1 core 300.0000 330.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_2 core 300.0000 360.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_3 core 300.0000 390.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_4 core 300.0000 420.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_5 core 300.0000 450.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_6 core 300.0000 480.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_7 core 300.0000 510.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_8 core 300.0000 540.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_9 core 300.0000 570.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_10 core 300.0000 600.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_11 core 300.0000 630.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_12 core 300.0000 660.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_13 core 300.0000 690.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_14 core 300.0000 720.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_15 core 300.0000 750.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_16 core 300.0000 780.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_17 core 300.0000 810.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_18 core 300.0000 840.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_19 core 300.0000 870.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_20 core 300.0000 900.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_21 core 300.0000 930.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_22 core 300.0000 960.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_23 core 300.0000 990.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_24 core 300.0000 1020.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_25 core 300.0000 1050.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_26 core 300.0000 1080.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_27 core 300.0000 1110.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_28 core 300.0000 1140.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_29 core 300.0000 1170.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_30 core 300.0000 1200.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_31 core 300.0000 1230.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_32 core 300.0000 1260.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_33 core 300.0000 1290.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_34 core 300.0000 1320.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_35 core 300.0000 1350.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_36 core 300.0000 1380.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_37 core 300.0000 1410.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_38 core 300.0000 1440.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_39 core 300.0000 1470.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_40 core 300.0000 1500.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_41 core 300.0000 1530.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_42 core 300.0000 1560.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_43 core 300.0000 1590.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_44 core 300.0000 1620.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_45 core 300.0000 1650.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_46 core 300.0000 1680.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_47 core 300.0000 1710.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_48 core 300.0000 1740.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_49 core 300.0000 1770.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_50 core 300.0000 1800.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_51 core 300.0000 1830.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_52 core 300.0000 1860.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_53 core 300.0000 1890.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_54 core 300.0000 1920.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_55 core 300.0000 1950.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_56 core 300.0000 1980.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_57 core 300.0000 2010.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_58 core 300.0000 2040.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_59 core 300.0000 2070.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_60 core 300.0000 2100.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_61 core 300.0000 2130.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_62 core 300.0000 2160.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_63 core 300.0000 2190.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_64 core 300.0000 2220.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_65 core 300.0000 2250.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_66 core 300.0000 2280.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_67 core 300.0000 2310.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_68 core 300.0000 2340.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_69 core 300.0000 2370.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_70 core 300.0000 2400.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_71 core 300.0000 2430.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_72 core 300.0000 2460.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_73 core 300.0000 2490.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_74 core 300.0000 2520.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_75 core 300.0000 2550.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_76 core 300.0000 2580.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_77 core 300.0000 2610.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_78 core 300.0000 2640.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_79 core 300.0000 2670.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_80 core 300.0000 2700.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_81 core 300.0000 2730.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_82 core 300.0000 2760.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_83 core 300.0000 2790.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_84 core 300.0000 2820.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_85 core 300.0000 2850.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_86 core 300.0000 2880.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_87 core 300.0000 2910.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_88 core 300.0000 2940.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_89 core 300.0000 2970.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_90 core 300.0000 3000.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_91 core 300.0000 3030.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_92 core 300.0000 3060.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_93 core 300.0000 3090.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_94 core 300.0000 3120.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_95 core 300.0000 3150.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_96 core 300.0000 3180.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_97 core 300.0000 3210.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_98 core 300.0000 3240.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_99 core 300.0000 3270.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_100 core 300.0000 3300.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_101 core 300.0000 3330.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_102 core 300.0000 3360.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_103 core 300.0000 3390.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_104 core 300.0000 3420.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_105 core 300.0000 3450.0000 N 1350 1 2.4000 0.0000
DefRow: ROW_106 core 300.0000 3480.0000 FS 1350 1 2.4000 0.0000
DefRow: ROW_107 core 300.0000 3510.0000 N 1350 1 2.4000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: X 1.2000 1600 2.4000 1 3
Track: Y 1.5000 1280 3.0000 1 3
Track: Y 1.5000 1280 3.0000 1 2
Track: X 1.2000 1600 2.4000 1 2
Track: X 1.2000 1600 2.4000 1 1
Track: Y 1.5000 1280 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 3817.2000 2 22.8000
GCellGrid: X 1.2000 160 24.0000
GCellGrid: X 0.0000 2 1.2000
GCellGrid: Y 3811.5000 2 28.5000
GCellGrid: Y 1.5000 128 30.0000
GCellGrid: Y 0.0000 2 1.5000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="shabang" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x7 orient=R0>
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .shabang30259.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: DN3412 PADNC 3450.0000 3540.0000 N R180 - 01
IO: DN2312 PADNC 3360.0000 3540.0000 N R180 - 01
IO: DN1312 PADNC 3270.0000 3540.0000 N R180 - 01
IO: DN0312 PADNC 3180.0000 3540.0000 N R180 - 01
IO: DN37 PADNC 3090.0000 3540.0000 N R180 - 01
IO: DN26 PADNC 3000.0000 3540.0000 N R180 - 01
IO: DN15 PADNC 2910.0000 3540.0000 N R180 - 01
IO: DN04 PADNC 2820.0000 3540.0000 N R180 - 01
IO: DN33 PADNC 2730.0000 3540.0000 N R180 - 01
IO: DN22 PADNC 2640.0000 3540.0000 N R180 - 01
IO: DN11 PADNC 2550.0000 3540.0000 N R180 - 01
IO: DN00 PADNC 2460.0000 3540.0000 N R180 - 01
IO: D22 PADNC 2370.0000 3540.0000 N R180 - 01
IO: D3 PADNC 2280.0000 3540.0000 N R180 - 01
IO: U4 PADINC 2190.0000 3540.0000 N R180 - 01
IO: D2 PADNC 2100.0000 3540.0000 N R180 - 01
IO: D23 PADNC 2010.0000 3540.0000 N R180 - 01
IO: P0 PADVDD 1920.0000 3540.0000 N R180 - 01
IO: G0 PADGND 1830.0000 3540.0000 N R180 - 01
IO: DN3 PADNC 1740.0000 3540.0000 N R180 - 01
IO: DN2 PADNC 1650.0000 3540.0000 N R180 - 01
IO: DN1 PADNC 1560.0000 3540.0000 N R180 - 01
IO: DN0 PADNC 1470.0000 3540.0000 N R180 - 01
IO: D24 PADNC 1380.0000 3540.0000 N R180 - 01
IO: D1 PADNC 1290.0000 3540.0000 N R180 - 01
IO: U3 PADOUT 1200.0000 3540.0000 N R180 - 01
IO: D0 PADNC 1110.0000 3540.0000 N R180 - 01
IO: D21 PADNC 1020.0000 3540.0000 N R180 - 01
IO: DN341 PADNC 930.0000 3540.0000 N R180 - 01
IO: DN231 PADNC 840.0000 3540.0000 N R180 - 01
IO: DN131 PADNC 750.0000 3540.0000 N R180 - 01
IO: DN031 PADNC 660.0000 3540.0000 N R180 - 01
IO: DN34 PADNC 570.0000 3540.0000 N R180 - 01
IO: DN23 PADNC 480.0000 3540.0000 N R180 - 01
IO: DN13 PADNC 390.0000 3540.0000 N R180 - 01
IO: DN03 PADNC 300.0000 3540.0000 N R0 - 01
IO: co2 PADFC 3540.0000 3540.0000 NE R270 - 01
IO: DW342 PADNC 0.0000 3450.0000 W R270 - 01
IO: DW232 PADNC 0.0000 3360.0000 W R270 - 01
IO: DW122 PADNC 0.0000 3270.0000 W R270 - 01
IO: DW012 PADNC 0.0000 3180.0000 W R270 - 01
IO: DW37 PADNC 0.0000 3090.0000 W R270 - 01
IO: DW27 PADNC 0.0000 3000.0000 W R270 - 01
IO: DW17 PADNC 0.0000 2910.0000 W R270 - 01
IO: DW07 PADNC 0.0000 2820.0000 W R270 - 01
IO: DW33 PADNC 0.0000 2730.0000 W R270 - 01
IO: DW22 PADNC 0.0000 2640.0000 W R270 - 01
IO: DW11 PADNC 0.0000 2550.0000 W R270 - 01
IO: DW00 PADNC 0.0000 2460.0000 W R270 - 01
IO: D19 PADNC 0.0000 2370.0000 W R270 - 01
IO: D7 PADNC 0.0000 2280.0000 W R270 - 01
IO: D13 PADOUT 0.0000 2190.0000 W R270 - 01
IO: D6 PADNC 0.0000 2100.0000 W R270 - 01
IO: D26 PADNC 0.0000 2010.0000 W R270 - 01
IO: P1 PADVDD 0.0000 1920.0000 W R270 - 01
IO: G1 PADGND 0.0000 1830.0000 W R270 - 01
IO: D25 PADNC 0.0000 1740.0000 W R270 - 01
IO: D5 PADNC 0.0000 1650.0000 W R270 - 01
IO: U1 PADOUT 0.0000 1560.0000 W R270 - 01
IO: D4 PADNC 0.0000 1470.0000 W R270 - 01
IO: D20 PADNC 0.0000 1380.0000 W R270 - 01
IO: DW341 PADNC 0.0000 1290.0000 W R270 - 01
IO: DW231 PADNC 0.0000 1200.0000 W R270 - 01
IO: DW121 PADNC 0.0000 1110.0000 W R270 - 01
IO: DW011 PADNC 0.0000 1020.0000 W R270 - 01
IO: DW34 PADNC 0.0000 930.0000 W R270 - 01
IO: DW23 PADNC 0.0000 840.0000 W R270 - 01
IO: DW12 PADNC 0.0000 750.0000 W R270 - 01
IO: DW01 PADNC 0.0000 660.0000 W R270 - 01
IO: DW3 PADNC 0.0000 570.0000 W R270 - 01
IO: DW2 PADNC 0.0000 480.0000 W R270 - 01
IO: DW1 PADNC 0.0000 390.0000 W R270 - 01
IO: DW0 PADNC 0.0000 300.0000 W R270 - 01
IO: co1 PADFC 0.0000 3540.0000 NW R0 - 01
IO: DS362 PADNC 3450.0000 0.0000 S R0 - 01
IO: DS262 PADNC 3360.0000 0.0000 S R0 - 01
IO: DS162 PADNC 3270.0000 0.0000 S R0 - 01
IO: DS062 PADNC 3180.0000 0.0000 S R0 - 01
IO: DS37 PADNC 3090.0000 0.0000 S R0 - 01
IO: DS27 PADNC 3000.0000 0.0000 S R0 - 01
IO: DS17 PADNC 2910.0000 0.0000 S R0 - 01
IO: DS07 PADNC 2820.0000 0.0000 S R0 - 01
IO: DS33 PADNC 2730.0000 0.0000 S R0 - 01
IO: DS22 PADNC 2640.0000 0.0000 S R0 - 01
IO: DS11 PADNC 2550.0000 0.0000 S R0 - 01
IO: DS00 PADNC 2460.0000 0.0000 S R0 - 01
IO: D18 PADNC 2370.0000 0.0000 S R0 - 01
IO: D11 PADNC 2280.0000 0.0000 S R0 - 01
IO: U2 PADOUT 2190.0000 0.0000 S R0 - 01
IO: D10 PADNC 2100.0000 0.0000 S R0 - 01
IO: D28 PADNC 2010.0000 0.0000 S R0 - 01
IO: G2 PADGND 1920.0000 0.0000 S R0 - 01
IO: P2 PADVDD 1830.0000 0.0000 S R0 - 01
IO: D27 PADNC 1740.0000 0.0000 S R0 - 01
IO: D9 PADNC 1650.0000 0.0000 S R0 - 01
IO: U6 PADINC 1560.0000 0.0000 S R0 - 01
IO: D8 PADNC 1470.0000 0.0000 S R0 - 01
IO: D17 PADNC 1380.0000 0.0000 S R0 - 01
IO: DS361 PADNC 1290.0000 0.0000 S R0 - 01
IO: DS261 PADNC 1200.0000 0.0000 S R0 - 01
IO: DS161 PADNC 1110.0000 0.0000 S R0 - 01
IO: DS061 PADNC 1020.0000 0.0000 S R0 - 01
IO: DS36 PADNC 930.0000 0.0000 S R0 - 01
IO: DS26 PADNC 840.0000 0.0000 S R0 - 01
IO: DS16 PADNC 750.0000 0.0000 S R0 - 01
IO: DS06 PADNC 660.0000 0.0000 S R0 - 01
IO: DS3 PADNC 570.0000 0.0000 S R0 - 01
IO: DS2 PADNC 480.0000 0.0000 S R0 - 01
IO: DS1 PADNC 390.0000 0.0000 S R0 - 01
IO: DS0 PADNC 300.0000 0.0000 S R180 - 01
IO: co3 PADFC 0.0000 0.0000 SW R90 - 01
IO: DE362 PADNC 3540.0000 3450.0000 E R90 - 01
IO: DE262 PADNC 3540.0000 3360.0000 E R90 - 01
IO: DE162 PADNC 3540.0000 3270.0000 E R90 - 01
IO: DE062 PADNC 3540.0000 3180.0000 E R90 - 01
IO: DE37 PADNC 3540.0000 3090.0000 E R90 - 01
IO: DE27 PADNC 3540.0000 3000.0000 E R90 - 01
IO: DE17 PADNC 3540.0000 2910.0000 E R90 - 01
IO: DE07 PADNC 3540.0000 2820.0000 E R90 - 01
IO: DE33 PADNC 3540.0000 2730.0000 E R90 - 01
IO: DE22 PADNC 3540.0000 2640.0000 E R90 - 01
IO: DE11 PADNC 3540.0000 2550.0000 E R90 - 01
IO: DE00 PADNC 3540.0000 2460.0000 E R90 - 01
IO: P3 PADVDD 3540.0000 2370.0000 E R90 - 01
IO: D29 PADNC 3540.0000 2280.0000 E R90 - 01
IO: U9 PADINC 3540.0000 2190.0000 E R90 - 01
IO: D15 PADNC 3540.0000 2100.0000 E R90 - 01
IO: U8 PADINC 3540.0000 2010.0000 E R90 - 01
IO: D14 PADNC 3540.0000 1920.0000 E R90 - 01
IO: D30 PADNC 3540.0000 1830.0000 E R90 - 01
IO: DE3 PADNC 3540.0000 1740.0000 E R90 - 01
IO: DE2 PADNC 3540.0000 1650.0000 E R90 - 01
IO: DE1 PADNC 3540.0000 1560.0000 E R90 - 01
IO: DE0 PADNC 3540.0000 1470.0000 E R90 - 01
IO: G3 PADGND 3540.0000 1380.0000 E R90 - 01
IO: U5 PADINC 3540.0000 1290.0000 E R90 - 01
IO: U7 PADINC 3540.0000 1200.0000 E R90 - 01
IO: D12 PADNC 3540.0000 1110.0000 E R90 - 01
IO: D16 PADNC 3540.0000 1020.0000 E R90 - 01
IO: DE361 PADNC 3540.0000 930.0000 E R90 - 01
IO: DE261 PADNC 3540.0000 840.0000 E R90 - 01
IO: DE161 PADNC 3540.0000 750.0000 E R90 - 01
IO: DE061 PADNC 3540.0000 660.0000 E R90 - 01
IO: DE36 PADNC 3540.0000 570.0000 E R90 - 01
IO: DE26 PADNC 3540.0000 480.0000 E R90 - 01
IO: DE16 PADNC 3540.0000 390.0000 E R90 - 01
IO: DE06 PADNC 3540.0000 300.0000 E R90 - 01
IO: co4 PADFC 3540.0000 0.0000 SE R180 - 01

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="w_clk" status="fixed" >
  </Pin>
  <Pin name="r_clk" status="fixed" >
  </Pin>
  <Pin name="n_rst" status="fixed" >
  </Pin>
  <Pin name="Ethernet_In" status="fixed" >
  </Pin>
  <Pin name="rx_d_plus" status="fixed" >
  </Pin>
  <Pin name="rx_d_minus" status="fixed" >
  </Pin>
  <Pin name="tx_d_plus" status="fixed" >
  </Pin>
  <Pin name="tx_d_minus" status="fixed" >
  </Pin>
  <Pin name="is_txing" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="shabang">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
