###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin6.ecn.purdue.edu)
#  Generated on:      Thu Apr 26 09:52:41 2018
#  Design:            shabang
#  Command:           floorPlan -r 1.0 0.4 40 40 40 40
###############################################################

Version: 8

Head Box: 0.0000 0.0000 3660.0000 10380.0000
IO Box: 90.0000 300.0000 3570.0000 10080.0000
Core Box: 91.2000 300.0000 3570.0000 10080.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 91.2000 300.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_1 core 91.2000 330.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_2 core 91.2000 360.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_3 core 91.2000 390.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_4 core 91.2000 420.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_5 core 91.2000 450.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_6 core 91.2000 480.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_7 core 91.2000 510.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_8 core 91.2000 540.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_9 core 91.2000 570.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_10 core 91.2000 600.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_11 core 91.2000 630.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_12 core 91.2000 660.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_13 core 91.2000 690.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_14 core 91.2000 720.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_15 core 91.2000 750.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_16 core 91.2000 780.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_17 core 91.2000 810.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_18 core 91.2000 840.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_19 core 91.2000 870.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_20 core 91.2000 900.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_21 core 91.2000 930.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_22 core 91.2000 960.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_23 core 91.2000 990.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_24 core 91.2000 1020.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_25 core 91.2000 1050.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_26 core 91.2000 1080.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_27 core 91.2000 1110.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_28 core 91.2000 1140.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_29 core 91.2000 1170.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_30 core 91.2000 1200.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_31 core 91.2000 1230.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_32 core 91.2000 1260.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_33 core 91.2000 1290.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_34 core 91.2000 1320.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_35 core 91.2000 1350.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_36 core 91.2000 1380.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_37 core 91.2000 1410.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_38 core 91.2000 1440.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_39 core 91.2000 1470.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_40 core 91.2000 1500.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_41 core 91.2000 1530.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_42 core 91.2000 1560.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_43 core 91.2000 1590.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_44 core 91.2000 1620.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_45 core 91.2000 1650.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_46 core 91.2000 1680.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_47 core 91.2000 1710.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_48 core 91.2000 1740.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_49 core 91.2000 1770.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_50 core 91.2000 1800.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_51 core 91.2000 1830.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_52 core 91.2000 1860.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_53 core 91.2000 1890.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_54 core 91.2000 1920.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_55 core 91.2000 1950.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_56 core 91.2000 1980.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_57 core 91.2000 2010.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_58 core 91.2000 2040.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_59 core 91.2000 2070.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_60 core 91.2000 2100.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_61 core 91.2000 2130.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_62 core 91.2000 2160.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_63 core 91.2000 2190.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_64 core 91.2000 2220.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_65 core 91.2000 2250.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_66 core 91.2000 2280.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_67 core 91.2000 2310.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_68 core 91.2000 2340.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_69 core 91.2000 2370.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_70 core 91.2000 2400.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_71 core 91.2000 2430.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_72 core 91.2000 2460.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_73 core 91.2000 2490.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_74 core 91.2000 2520.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_75 core 91.2000 2550.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_76 core 91.2000 2580.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_77 core 91.2000 2610.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_78 core 91.2000 2640.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_79 core 91.2000 2670.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_80 core 91.2000 2700.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_81 core 91.2000 2730.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_82 core 91.2000 2760.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_83 core 91.2000 2790.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_84 core 91.2000 2820.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_85 core 91.2000 2850.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_86 core 91.2000 2880.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_87 core 91.2000 2910.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_88 core 91.2000 2940.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_89 core 91.2000 2970.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_90 core 91.2000 3000.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_91 core 91.2000 3030.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_92 core 91.2000 3060.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_93 core 91.2000 3090.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_94 core 91.2000 3120.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_95 core 91.2000 3150.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_96 core 91.2000 3180.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_97 core 91.2000 3210.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_98 core 91.2000 3240.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_99 core 91.2000 3270.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_100 core 91.2000 3300.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_101 core 91.2000 3330.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_102 core 91.2000 3360.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_103 core 91.2000 3390.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_104 core 91.2000 3420.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_105 core 91.2000 3450.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_106 core 91.2000 3480.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_107 core 91.2000 3510.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_108 core 91.2000 3540.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_109 core 91.2000 3570.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_110 core 91.2000 3600.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_111 core 91.2000 3630.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_112 core 91.2000 3660.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_113 core 91.2000 3690.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_114 core 91.2000 3720.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_115 core 91.2000 3750.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_116 core 91.2000 3780.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_117 core 91.2000 3810.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_118 core 91.2000 3840.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_119 core 91.2000 3870.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_120 core 91.2000 3900.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_121 core 91.2000 3930.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_122 core 91.2000 3960.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_123 core 91.2000 3990.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_124 core 91.2000 4020.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_125 core 91.2000 4050.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_126 core 91.2000 4080.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_127 core 91.2000 4110.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_128 core 91.2000 4140.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_129 core 91.2000 4170.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_130 core 91.2000 4200.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_131 core 91.2000 4230.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_132 core 91.2000 4260.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_133 core 91.2000 4290.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_134 core 91.2000 4320.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_135 core 91.2000 4350.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_136 core 91.2000 4380.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_137 core 91.2000 4410.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_138 core 91.2000 4440.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_139 core 91.2000 4470.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_140 core 91.2000 4500.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_141 core 91.2000 4530.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_142 core 91.2000 4560.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_143 core 91.2000 4590.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_144 core 91.2000 4620.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_145 core 91.2000 4650.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_146 core 91.2000 4680.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_147 core 91.2000 4710.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_148 core 91.2000 4740.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_149 core 91.2000 4770.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_150 core 91.2000 4800.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_151 core 91.2000 4830.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_152 core 91.2000 4860.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_153 core 91.2000 4890.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_154 core 91.2000 4920.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_155 core 91.2000 4950.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_156 core 91.2000 4980.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_157 core 91.2000 5010.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_158 core 91.2000 5040.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_159 core 91.2000 5070.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_160 core 91.2000 5100.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_161 core 91.2000 5130.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_162 core 91.2000 5160.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_163 core 91.2000 5190.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_164 core 91.2000 5220.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_165 core 91.2000 5250.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_166 core 91.2000 5280.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_167 core 91.2000 5310.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_168 core 91.2000 5340.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_169 core 91.2000 5370.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_170 core 91.2000 5400.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_171 core 91.2000 5430.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_172 core 91.2000 5460.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_173 core 91.2000 5490.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_174 core 91.2000 5520.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_175 core 91.2000 5550.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_176 core 91.2000 5580.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_177 core 91.2000 5610.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_178 core 91.2000 5640.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_179 core 91.2000 5670.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_180 core 91.2000 5700.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_181 core 91.2000 5730.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_182 core 91.2000 5760.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_183 core 91.2000 5790.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_184 core 91.2000 5820.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_185 core 91.2000 5850.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_186 core 91.2000 5880.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_187 core 91.2000 5910.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_188 core 91.2000 5940.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_189 core 91.2000 5970.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_190 core 91.2000 6000.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_191 core 91.2000 6030.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_192 core 91.2000 6060.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_193 core 91.2000 6090.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_194 core 91.2000 6120.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_195 core 91.2000 6150.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_196 core 91.2000 6180.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_197 core 91.2000 6210.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_198 core 91.2000 6240.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_199 core 91.2000 6270.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_200 core 91.2000 6300.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_201 core 91.2000 6330.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_202 core 91.2000 6360.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_203 core 91.2000 6390.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_204 core 91.2000 6420.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_205 core 91.2000 6450.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_206 core 91.2000 6480.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_207 core 91.2000 6510.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_208 core 91.2000 6540.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_209 core 91.2000 6570.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_210 core 91.2000 6600.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_211 core 91.2000 6630.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_212 core 91.2000 6660.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_213 core 91.2000 6690.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_214 core 91.2000 6720.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_215 core 91.2000 6750.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_216 core 91.2000 6780.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_217 core 91.2000 6810.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_218 core 91.2000 6840.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_219 core 91.2000 6870.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_220 core 91.2000 6900.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_221 core 91.2000 6930.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_222 core 91.2000 6960.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_223 core 91.2000 6990.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_224 core 91.2000 7020.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_225 core 91.2000 7050.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_226 core 91.2000 7080.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_227 core 91.2000 7110.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_228 core 91.2000 7140.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_229 core 91.2000 7170.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_230 core 91.2000 7200.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_231 core 91.2000 7230.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_232 core 91.2000 7260.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_233 core 91.2000 7290.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_234 core 91.2000 7320.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_235 core 91.2000 7350.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_236 core 91.2000 7380.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_237 core 91.2000 7410.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_238 core 91.2000 7440.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_239 core 91.2000 7470.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_240 core 91.2000 7500.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_241 core 91.2000 7530.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_242 core 91.2000 7560.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_243 core 91.2000 7590.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_244 core 91.2000 7620.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_245 core 91.2000 7650.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_246 core 91.2000 7680.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_247 core 91.2000 7710.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_248 core 91.2000 7740.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_249 core 91.2000 7770.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_250 core 91.2000 7800.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_251 core 91.2000 7830.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_252 core 91.2000 7860.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_253 core 91.2000 7890.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_254 core 91.2000 7920.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_255 core 91.2000 7950.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_256 core 91.2000 7980.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_257 core 91.2000 8010.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_258 core 91.2000 8040.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_259 core 91.2000 8070.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_260 core 91.2000 8100.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_261 core 91.2000 8130.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_262 core 91.2000 8160.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_263 core 91.2000 8190.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_264 core 91.2000 8220.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_265 core 91.2000 8250.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_266 core 91.2000 8280.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_267 core 91.2000 8310.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_268 core 91.2000 8340.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_269 core 91.2000 8370.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_270 core 91.2000 8400.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_271 core 91.2000 8430.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_272 core 91.2000 8460.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_273 core 91.2000 8490.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_274 core 91.2000 8520.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_275 core 91.2000 8550.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_276 core 91.2000 8580.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_277 core 91.2000 8610.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_278 core 91.2000 8640.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_279 core 91.2000 8670.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_280 core 91.2000 8700.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_281 core 91.2000 8730.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_282 core 91.2000 8760.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_283 core 91.2000 8790.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_284 core 91.2000 8820.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_285 core 91.2000 8850.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_286 core 91.2000 8880.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_287 core 91.2000 8910.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_288 core 91.2000 8940.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_289 core 91.2000 8970.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_290 core 91.2000 9000.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_291 core 91.2000 9030.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_292 core 91.2000 9060.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_293 core 91.2000 9090.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_294 core 91.2000 9120.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_295 core 91.2000 9150.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_296 core 91.2000 9180.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_297 core 91.2000 9210.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_298 core 91.2000 9240.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_299 core 91.2000 9270.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_300 core 91.2000 9300.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_301 core 91.2000 9330.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_302 core 91.2000 9360.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_303 core 91.2000 9390.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_304 core 91.2000 9420.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_305 core 91.2000 9450.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_306 core 91.2000 9480.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_307 core 91.2000 9510.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_308 core 91.2000 9540.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_309 core 91.2000 9570.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_310 core 91.2000 9600.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_311 core 91.2000 9630.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_312 core 91.2000 9660.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_313 core 91.2000 9690.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_314 core 91.2000 9720.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_315 core 91.2000 9750.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_316 core 91.2000 9780.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_317 core 91.2000 9810.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_318 core 91.2000 9840.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_319 core 91.2000 9870.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_320 core 91.2000 9900.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_321 core 91.2000 9930.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_322 core 91.2000 9960.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_323 core 91.2000 9990.0000 N 1449 1 2.4000 0.0000
DefRow: ROW_324 core 91.2000 10020.0000 FS 1449 1 2.4000 0.0000
DefRow: ROW_325 core 91.2000 10050.0000 N 1449 1 2.4000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: X 1.2000 1525 2.4000 1 3
Track: Y 1.5000 3460 3.0000 1 3
Track: Y 1.5000 3460 3.0000 1 2
Track: X 1.2000 1525 2.4000 1 2
Track: X 1.2000 1525 2.4000 1 1
Track: Y 1.5000 3460 3.0000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 3649.2000 2 10.8000
GCellGrid: X 1.2000 153 24.0000
GCellGrid: X 0.0000 2 1.2000
GCellGrid: Y 10351.5000 2 28.5000
GCellGrid: Y 1.5000 346 30.0000
GCellGrid: Y 0.0000 2 1.5000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="shabang" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x7 orient=R0>
	<PinLayer side="N" Metal2=yes />
	<PinLayer side="W" Metal3=yes />
	<PinLayer side="S" Metal2=yes />
	<PinLayer side="E" Metal3=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .shabang5115.rs.fp.spr

#######################################################################################
#  IO: <instName> <cellName> <lx> <ly> <side> <orient> {-power|-ground|-} \           #
#      [isCovered isPrePlaced]                                                        #
#  IOPin: <pinName> <x> <y> <side> <layerId> <width> <depth> {placed|fixed|cover|-} <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                  #
#    PinPoly: <nrPt> <x1> <y1> <x2> <y2> ...<xn> <yn>                                 #
#######################################################################################
IO: NR16 PADNC 3270.0000 10080.0000 N R0 - 01
IO: NR15 PADNC 3180.0000 10080.0000 N R0 - 01
IO: NR14 PADNC 3090.0000 10080.0000 N R0 - 01
IO: NR13 PADNC 3000.0000 10080.0000 N R0 - 01
IO: NR12 PADNC 2910.0000 10080.0000 N R0 - 01
IO: NR11 PADNC 2820.0000 10080.0000 N R0 - 01
IO: NR10 PADNC 2730.0000 10080.0000 N R0 - 01
IO: U4 PADINC 2640.0000 10080.0000 N R0 - 01
IO: NR08 PADNC 2550.0000 10080.0000 N R0 - 01
IO: NR07 PADNC 2460.0000 10080.0000 N R0 - 01
IO: NR06 PADNC 2370.0000 10080.0000 N R0 - 01
IO: NR05 PADNC 2280.0000 10080.0000 N R0 - 01
IO: NR04 PADNC 2190.0000 10080.0000 N R0 - 01
IO: NR03 PADNC 2100.0000 10080.0000 N R0 - 01
IO: NR02 PADNC 2010.0000 10080.0000 N R0 - 01
IO: NR01 PADNC 1920.0000 10080.0000 N R0 - 01
IO: P0 PADVDD 1830.0000 10080.0000 N R0 - 01
IO: G0 PADGND 1740.0000 10080.0000 N R0 - 01
IO: NL16 PADNC 1650.0000 10080.0000 N R0 - 01
IO: NL15 PADNC 1560.0000 10080.0000 N R0 - 01
IO: NL14 PADNC 1470.0000 10080.0000 N R0 - 01
IO: NL13 PADNC 1380.0000 10080.0000 N R0 - 01
IO: NL12 PADNC 1290.0000 10080.0000 N R0 - 01
IO: NL11 PADNC 1200.0000 10080.0000 N R0 - 01
IO: NL10 PADNC 1110.0000 10080.0000 N R0 - 01
IO: U1 PADOUT 1020.0000 10080.0000 N R0 - 01
IO: NL08 PADNC 930.0000 10080.0000 N R0 - 01
IO: NL07 PADNC 840.0000 10080.0000 N R0 - 01
IO: NL06 PADNC 750.0000 10080.0000 N R0 - 01
IO: NL05 PADNC 660.0000 10080.0000 N R0 - 01
IO: NL04 PADNC 570.0000 10080.0000 N R0 - 01
IO: NL03 PADNC 480.0000 10080.0000 N R0 - 01
IO: NL02 PADNC 390.0000 10080.0000 N R0 - 01
IO: NL01 PADNC 300.0000 10080.0000 N R0 - 01
IO: co2 PADFC 3360.0000 10080.0000 NE R270 - 01
IO: WR16 PADNC 0.0000 9780.0000 W R0 - 01
IO: WR15 PADNC 0.0000 9480.0000 W R0 - 01
IO: WR14 PADNC 0.0000 9180.0000 W R0 - 01
IO: WR13 PADNC 0.0000 8880.0000 W R0 - 01
IO: WR12 PADNC 0.0000 8580.0000 W R0 - 01
IO: WR11 PADNC 0.0000 8280.0000 W R0 - 01
IO: WR10 PADNC 0.0000 7980.0000 W R0 - 01
IO: WR09 PADNC 0.0000 7680.0000 W R0 - 01
IO: WR08 PADNC 0.0000 7380.0000 W R0 - 01
IO: U9 PADINC 0.0000 7080.0000 W R0 - 01
IO: WR06 PADNC 0.0000 6780.0000 W R0 - 01
IO: WR05 PADNC 0.0000 6480.0000 W R0 - 01
IO: WR04 PADNC 0.0000 6180.0000 W R0 - 01
IO: WR03 PADNC 0.0000 5880.0000 W R0 - 01
IO: WR02 PADNC 0.0000 5580.0000 W R0 - 01
IO: WR01 PADNC 0.0000 5280.0000 W R0 - 01
IO: P1 PADVDD 0.0000 5190.0000 W R90 - 01
IO: G1 PADGND 0.0000 5100.0000 W R90 - 01
IO: WL16 PADNC 0.0000 4800.0000 W R0 - 01
IO: WL15 PADNC 0.0000 4500.0000 W R0 - 01
IO: WL14 PADNC 0.0000 4200.0000 W R0 - 01
IO: WL13 PADNC 0.0000 3900.0000 W R0 - 01
IO: U3 PADOUT 0.0000 3600.0000 W R0 - 01
IO: WL11 PADNC 0.0000 3300.0000 W R0 - 01
IO: WL10 PADNC 0.0000 3000.0000 W R0 - 01
IO: WL09 PADNC 0.0000 2700.0000 W R0 - 01
IO: WL08 PADNC 0.0000 2400.0000 W R0 - 01
IO: WL07 PADNC 0.0000 2100.0000 W R0 - 01
IO: WL06 PADNC 0.0000 1800.0000 W R0 - 01
IO: U2 PADOUT 0.0000 1500.0000 W R0 - 01
IO: WL04 PADNC 0.0000 1200.0000 W R0 - 01
IO: WL03 PADNC 0.0000 900.0000 W R0 - 01
IO: WL02 PADNC 0.0000 600.0000 W R0 - 01
IO: WL01 PADNC 0.0000 300.0000 W R0 - 01
IO: co1 PADFC 0.0000 10080.0000 NW R0 - 01
IO: SR16 PADNC 3270.0000 0.0000 S R0 - 01
IO: SR15 PADNC 3180.0000 0.0000 S R0 - 01
IO: SR14 PADNC 3090.0000 0.0000 S R0 - 01
IO: SR13 PADNC 3000.0000 0.0000 S R0 - 01
IO: SR12 PADNC 2910.0000 0.0000 S R0 - 01
IO: SR11 PADNC 2820.0000 0.0000 S R0 - 01
IO: SR10 PADNC 2730.0000 0.0000 S R0 - 01
IO: SR09 PADNC 2640.0000 0.0000 S R0 - 01
IO: SR08 PADNC 2550.0000 0.0000 S R0 - 01
IO: SR07 PADNC 2460.0000 0.0000 S R0 - 01
IO: SR06 PADNC 2370.0000 0.0000 S R0 - 01
IO: SR05 PADNC 2280.0000 0.0000 S R0 - 01
IO: SR04 PADNC 2190.0000 0.0000 S R0 - 01
IO: SR03 PADNC 2100.0000 0.0000 S R0 - 01
IO: SR02 PADNC 2010.0000 0.0000 S R0 - 01
IO: SR01 PADNC 1920.0000 0.0000 S R0 - 01
IO: P2 PADVDD 1830.0000 0.0000 S R180 - 01
IO: G2 PADGND 1740.0000 0.0000 S R180 - 01
IO: SL16 PADNC 1650.0000 0.0000 S R0 - 01
IO: SL15 PADNC 1560.0000 0.0000 S R0 - 01
IO: SL14 PADNC 1470.0000 0.0000 S R0 - 01
IO: SL13 PADNC 1380.0000 0.0000 S R0 - 01
IO: SL12 PADNC 1290.0000 0.0000 S R0 - 01
IO: SL11 PADNC 1200.0000 0.0000 S R0 - 01
IO: U6 PADINC 1110.0000 0.0000 S R0 - 01
IO: SL09 PADNC 1020.0000 0.0000 S R0 - 01
IO: SL08 PADNC 930.0000 0.0000 S R0 - 01
IO: SL07 PADNC 840.0000 0.0000 S R0 - 01
IO: SL06 PADNC 750.0000 0.0000 S R0 - 01
IO: SL05 PADNC 660.0000 0.0000 S R0 - 01
IO: U5 PADINC 570.0000 0.0000 S R0 - 01
IO: SL03 PADNC 480.0000 0.0000 S R0 - 01
IO: SL02 PADNC 390.0000 0.0000 S R0 - 01
IO: SL01 PADNC 300.0000 0.0000 S R0 - 01
IO: co3 PADFC 0.0000 0.0000 SW R90 - 01
IO: ER16 PADNC 3570.0000 9780.0000 E R0 - 01
IO: ER15 PADNC 3570.0000 9480.0000 E R0 - 01
IO: ER14 PADNC 3570.0000 9180.0000 E R0 - 01
IO: ER13 PADNC 3570.0000 8880.0000 E R0 - 01
IO: ER12 PADNC 3570.0000 8580.0000 E R0 - 01
IO: U8 PADINC 3570.0000 8280.0000 E R0 - 01
IO: ER10 PADNC 3570.0000 7980.0000 E R0 - 01
IO: ER09 PADNC 3570.0000 7680.0000 E R0 - 01
IO: ER08 PADNC 3570.0000 7380.0000 E R0 - 01
IO: ER07 PADNC 3570.0000 7080.0000 E R0 - 01
IO: ER06 PADNC 3570.0000 6780.0000 E R0 - 01
IO: ER05 PADNC 3570.0000 6480.0000 E R0 - 01
IO: ER04 PADNC 3570.0000 6180.0000 E R0 - 01
IO: ER03 PADNC 3570.0000 5880.0000 E R0 - 01
IO: ER02 PADNC 3570.0000 5580.0000 E R0 - 01
IO: ER01 PADNC 3570.0000 5280.0000 E R0 - 01
IO: P3 PADVDD 3360.0000 5190.0000 E R270 - 01
IO: G3 PADGND 3360.0000 5100.0000 E R270 - 01
IO: EL16 PADNC 3570.0000 4800.0000 E R0 - 01
IO: EL15 PADNC 3570.0000 4500.0000 E R0 - 01
IO: EL14 PADNC 3570.0000 4200.0000 E R0 - 01
IO: EL13 PADNC 3570.0000 3900.0000 E R0 - 01
IO: EL12 PADNC 3570.0000 3600.0000 E R0 - 01
IO: EL11 PADNC 3570.0000 3300.0000 E R0 - 01
IO: EL10 PADNC 3570.0000 3000.0000 E R0 - 01
IO: EL09 PADNC 3570.0000 2700.0000 E R0 - 01
IO: EL08 PADNC 3570.0000 2400.0000 E R0 - 01
IO: U7 PADINC 3570.0000 2100.0000 E R0 - 01
IO: EL06 PADNC 3570.0000 1800.0000 E R0 - 01
IO: EL05 PADNC 3570.0000 1500.0000 E R0 - 01
IO: EL04 PADNC 3570.0000 1200.0000 E R0 - 01
IO: EL03 PADNC 3570.0000 900.0000 E R0 - 01
IO: EL02 PADNC 3570.0000 600.0000 E R0 - 01
IO: EL01 PADNC 3570.0000 300.0000 E R0 - 01
IO: co4 PADFC 3360.0000 0.0000 SE R180 - 01

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="w_clk" status="fixed" >
  </Pin>
  <Pin name="r_clk" status="fixed" >
  </Pin>
  <Pin name="n_rst" status="fixed" >
  </Pin>
  <Pin name="Ethernet_In" status="fixed" >
  </Pin>
  <Pin name="rx_d_plus" status="fixed" >
  </Pin>
  <Pin name="rx_d_minus" status="fixed" >
  </Pin>
  <Pin name="tx_d_plus" status="fixed" >
  </Pin>
  <Pin name="tx_d_minus" status="fixed" >
  </Pin>
  <Pin name="is_txing" status="fixed" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="shabang">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
