/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ecegrid-thin7.ecn.purdue.edu)
#  Generated on:      Mon Apr 23 19:27:50 2018
#  Design:            shabang
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : K-2015.06-SP1
// Date      : Mon Apr 23 19:25:49 2018
/////////////////////////////////////////////////////////////
module shabang_t (
	w_clk, 
	r_clk, 
	n_rst, 
	Ethernet_In, 
	rx_d_plus, 
	rx_d_minus, 
	tx_d_plus, 
	tx_d_minus, 
	is_txing);
   input w_clk;
   input r_clk;
   input n_rst;
   input Ethernet_In;
   input rx_d_plus;
   input rx_d_minus;
   output tx_d_plus;
   output tx_d_minus;
   output is_txing;

   // Internal wires
   wire r_en;
   wire fifo_ready;
   wire [7:0] r_data;

   Packet_Storage Ethernet_input (.w_clk(w_clk),
	.r_clk(r_clk),
	.n_rst(n_rst),
	.Ethernet_In(Ethernet_In),
	.r_en(r_en),
	.ready(fifo_ready),
	.r_data(r_data));
   transceiver USB_output (.clk(r_clk),
	.n_rst(n_rst),
	.FIFO_byte(r_data),
	.fifo_ready(fifo_ready),
	.tx_d_plus(tx_d_plus),
	.tx_d_minus(tx_d_minus),
	.rx_d_plus(rx_d_plus),
	.rx_d_minus(rx_d_minus),
	.fifo_r_enable(r_en),
	.is_txing(is_txing));
endmodule

module shabang (
	w_clk, 
	r_clk, 
	n_rst, 
	Ethernet_In, 
	rx_d_plus, 
	rx_d_minus, 
	tx_d_plus, 
	tx_d_minus, 
	is_txing);
   input w_clk;
   input r_clk;
   input n_rst;
   input Ethernet_In;
   input rx_d_plus;
   input rx_d_minus;
   output tx_d_plus;
   output tx_d_minus;
   output is_txing;

   // Internal wires
   wire nw_clk;
   wire nr_clk;
   wire nn_rst;
   wire nEthernet_In;
   wire nrx_d_plus;
   wire nrx_d_minus;
   wire ntx_d_plus;
   wire ntx_d_minus;
   wire nis_txing;

   shabang_t I0 (.w_clk(nw_clk),
	.r_clk(nr_clk),
	.n_rst(nn_rst),
	.Ethernet_In(nEthernet_In),
	.rx_d_plus(nrx_d_plus),
	.rx_d_minus(nrx_d_minus),
	.tx_d_plus(ntx_d_plus),
	.tx_d_minus(ntx_d_minus),
	.is_txing(nis_txing));
   PADOUT U1 (.DO(nis_txing),
	.YPAD(is_txing));
   PADOUT U2 (.DO(ntx_d_minus),
	.YPAD(tx_d_minus));
   PADOUT U3 (.DO(ntx_d_plus),
	.YPAD(tx_d_plus));
   PADINC U4 (.DI(nEthernet_In),
	.YPAD(Ethernet_In));
   PADINC U5 (.DI(nn_rst),
	.YPAD(n_rst));
   PADINC U6 (.DI(nr_clk),
	.YPAD(r_clk));
   PADINC U7 (.DI(nrx_d_minus),
	.YPAD(rx_d_minus));
   PADINC U8 (.DI(nrx_d_plus),
	.YPAD(rx_d_plus));
   PADINC U9 (.DI(nw_clk),
	.YPAD(w_clk));
endmodule

